import { Chain } from "../../../networks/constant";

export const CoingeckoChainCategoryId = {
  [Chain.ABSTRACT]: "abstract-ecosystem",
  [Chain.ARBITRUM]: "arbitrum-ecosystem",
  [Chain.AVALANCHE]: "avalanche-ecosystem",
  [Chain.BASE]: "base-ecosystem",
  [Chain.BERACHAIN]: "berachain-ecosystem",
  [Chain.BITROCK]: "bitrock-ecosystem",
  [Chain.BNBCHAIN]: "binance-smart-chain",
  [Chain.CRONOS]: "cronos-ecosystem",
  [Chain.CRONOS_ZKEVM]: "cronos-zkevm-ecosystem",
  [Chain.ETHEREUM]: "ethereum-ecosystem",
  [Chain.FANTOM]: "fantom-ecosystem",
  [Chain.GNOSIS]: "xdai-ecosystem",
  [Chain.HECO]: "heco-chain-ecosystem",
  [Chain.HYPER_EVM]: "hyperevm-ecosystem",
  [Chain.LINEA]: "linea-ecosystem",
  [Chain.METIS]: "metis-ecosystem",
  [Chain.NEON]: "neon-ecosystem",
  [Chain.OPBNB]: "opbnb-ecosystem",
  [Chain.OPTIMISM]: "optimism-ecosystem",
  [Chain.POLYGON]: "polygon-ecosystem",
  [Chain.POLYGON_ZKEVM]: "polygon-zkevm-ecosystem",
  [Chain.SEI]: "sei-v2-ecosystem",
  [Chain.SONIC]: "sonic-ecosystem",
  [Chain.STORY]: "story-ecosystem",
  [Chain.TRON]: "tron-ecosystem",
};

export const CoingeckoPlatformId = {
  [Chain.ABSTRACT]: "abstract",
  [Chain.ARBITRUM]: "arbitrum-one",
  [Chain.AVALANCHE]: "avalanche",
  [Chain.BASE]: "base",
  [Chain.BERACHAIN]: "berachain",
  [Chain.BITROCK]: "bitrock",
  [Chain.BNBCHAIN]: "binance-smart-chain",
  [Chain.CRONOS]: "cronos",
  [Chain.CRONOS_ZKEVM]: "cronos-zkevm",
  [Chain.ETHEREUM]: "ethereum",
  [Chain.FANTOM]: "fantom",
  [Chain.GNOSIS]: "xdai",
  [Chain.HECO]: "heco-token",
  [Chain.HYPER_EVM]: "hyperevm",
  [Chain.LINEA]: "linea",
  [Chain.METIS]: "metis-andromeda",
  [Chain.NEON]: "neon-evm",
  [Chain.OPBNB]: "opbnb",
  [Chain.OPTIMISM]: "optimistic-ethereum",
  [Chain.POLYGON]: "polygon-pos",
  [Chain.POLYGON_ZKEVM]: "polygon-zkevm",
  [Chain.SEI]: "sei-v2",
  [Chain.SONIC]: "sonic",
  [Chain.STORY]: "story",
  [Chain.TRON]: "tron",
};


// bridge 1 LINK from bsc to USDT on sonic
// 0x691889F5944126906F0051c5ca087e975BADABb3